{
    "name": "Web Responsive",
    "category": "Website",
    "license": "OPL-1",
    "installable": True,
    "depends": ["web", "mail"],
    "excludes": ["web_enterprise"],
    "data": [
        "views/res_users.xml",
        "views/web.xml",
        "views/res_config_settings_view.xml",
    ],
    "assets": {

        'web._assets_primary_variables': [
            ('prepend', 'web_responsive/static/src/scss/primary_variables.scss'),
        ],
        'web._assets_secondary_variables': [
            'web_responsive/static/src/scss/secondary_variables.scss',
        ],
        "web.assets_frontend": [
            "/web_responsive/static/src/legacy/js/website_apps_menu.js",
            "/web_responsive/static/src/legacy/scss/website_apps_menu.scss",
        ],
        "web.assets_backend": [
            "/web_responsive/static/src/scss/sticky_header.scss",
            "/web_responsive/static/src/legacy/scss/web_responsive.scss",
            "/web_responsive/static/src/legacy/js/web_responsive.js",
            "/web_responsive/static/src/legacy/scss/kanban_view_mobile.scss",
            "/web_responsive/static/src/legacy/js/kanban_renderer_mobile.js",
            "/web_responsive/static/src/components/ui_context.esm.js",
            "/web_responsive/static/src/components/apps_menu/apps_menu.scss",
            "/web_responsive/static/src/components/apps_menu/apps_menu.esm.js",
            "/web_responsive/static/src/components/navbar/main_navbar.scss",
            "/web_responsive/static/src/components/control_panel/control_panel.scss",
            "/web_responsive/static/src/components/control_panel/control_panel.esm.js",
            "/web_responsive/static/src/components/search_panel/search_panel.scss",
            "/web_responsive/static/src/components/search_panel/search_panel.esm.js",
            "/web_responsive/static/src/components/attachment_viewer/attachment_viewer.scss",
            "/web_responsive/static/src/components/attachment_viewer/attachment_viewer.esm.js",
            "/web_responsive/static/src/components/hotkey/hotkey.scss",
            ('replace', 'web/static/src/webclient/webclient_extra.scss',
             'web_responsive/static/src/scss/webclient.scss'),
            # ('replace', 'web/static/src/webclient/webclient_layout.scss', 'web_responsive/static/src/webclient/webclient_layout.scss'),
            ('replace', 'web/static/src/legacy/scss/dropdown_extra.scss',
             'web_responsive/static/src/scss/fields.scss'),
            ('replace', 'web/static/src/legacy/scss/fields_extra.scss',
             'web_responsive/static/src/scss/form_view.scss'),
            ('replace', 'web/static/src/legacy/scss/form_view_extra.scss',
             'web_responsive/static/src/scss/list_view.scss'),
            ('replace', 'web/static/src/legacy/scss/list_view_extra.scss',
             'web_responsive/static/src/scss/search_view.scss'),
            ('replace', 'web/static/src/search/search_panel/search_view_extra.scss',
             'web_responsive/static/src/scss/dropdown.scss'),
            "/web_responsive/static/src/scss/chatter_position.scss",
            "/web_responsive/static/src/scss/attachment_viewer.scss",
            "/web_responsive/static/src/js/form_chatter_position.js",
            '/web_responsive/static/src/js/block_ui.js',
            '/web_responsive/static/src/scss/block_ui.scss',
            '/web_responsive/static/src/js/res_config_settings.js',
            'web_responsive/static/src/js/FieldProgressBar.js',
            'web_responsive/static/src/js/user_menu.js',
        ],
        "web.assets_qweb": [
            "/web_responsive/static/src/legacy/xml/form_buttons.xml",
            "/web_responsive/static/src/components/apps_menu/apps_menu.xml",
            "/web_responsive/static/src/components/control_panel/control_panel.xml",
            "/web_responsive/static/src/components/navbar/main_navbar.xml",
            "/web_responsive/static/src/components/search_panel/search_panel.xml",
            "/web_responsive/static/src/components/attachment_viewer/attachment_viewer.xml",
            "/web_responsive/static/src/components/hotkey/hotkey.xml",
            "/web_responsive/static/src/xml/form_buttons.xml",
            "/web_responsive/static/src/xml/loading.xml",
        ],
        'web.assets_common': [
            'web_responsive/static/src/scss/fonts.scss',
        ],
        'web.report_assets_common': [
            'web_responsive/static/src/scss/fonts.scss',
        ],
    },
    'post_init_hook': 'icons_post_init_hook',
    "sequence": 1,
}
