name: Odoolint Check
on:
  pull_request:
    branches: [ main, dev, release, staging ]

jobs:
  odoolint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install odoolint
    - name: Run Odoolint
      run: odoolint
